import { Category, Article, FAQ } from './types';

export const LANGUAGES = [
  { code: 'en', name: 'English' },
  { code: 'es', name: 'Español' },
  { code: 'ur', name: 'اردو' }
] as const;

export const translations = {
  en: {
    title: 'GlobalConverter',
    subtitle: 'Professional Unit & Currency Converter',
    home: 'Home',
    converters: 'Converters',
    calculators: 'Calculators',
    guides: 'Blog Guides',
    admin: 'Admin Console',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    username: 'Username or Email',
    password: 'Password',
    login: 'Sign In Securely',
    forgotPassword: 'Forgot Password?',
    fullNameLabel: 'Registered Full Name (for Identity Verification)',
    newPasswordLabel: 'New Password',
    resetPasswordBtn: 'Verify Identity & Reset Password',
    backToLogin: 'Back to Sign In',
    selectLang: 'Language',
    categories: 'Categories',
    latestArticles: 'Latest SEO Guides & Formulas',
    frequentlyAsked: 'Frequently Asked Questions',
    conversionHistory: 'Conversion Real-time Log',
    from: 'From',
    to: 'To',
    value: 'Value',
    result: 'Converted Result',
    convertBtn: 'Calculate & Convert',
    formula: 'Conversion Formula Used:',
    example: 'Practical Example:',
    views: 'views',
    searchPlaceholder: 'Search unit formulas, calculators, or SEO guides...',
    adminWelcome: 'Welcome to Administrator Panel',
    visitorLogs: 'Visitor Analytics Log',
    siteSettings: 'Site Settings',
    adManagement: 'Ad Management',
    manageArticles: 'Manage SEO Articles',
    manageFAQs: 'Manage FAQs',
    saveSettings: 'Save Settings Changes',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    createArticle: 'Create New SEO Article',
    createFAQ: 'Create New FAQ',
    ipAddress: 'IP Address',
    userAgent: 'Web browser User Agent',
    visitedAt: 'Visited Time',
    path: 'Requested Web Path'
  },
  es: {
    title: 'GlobalConverter',
    subtitle: 'Conversor Profesional de Unidades y Divisas',
    home: 'Inicio',
    converters: 'Conversores',
    calculators: 'Calculadoras',
    guides: 'Guías de Blog',
    admin: 'Panel de Administración',
    signIn: 'Iniciar Sesión',
    signOut: 'Cerrar Sesión',
    username: 'Usuario o Correo electrónico',
    password: 'Contraseña',
    login: 'Iniciar Sesión con Seguridad',
    forgotPassword: '¿Olvidó su contraseña?',
    fullNameLabel: 'Nombre Completo Registrado (para Verificar Identidad)',
    newPasswordLabel: 'Nueva Contraseña',
    resetPasswordBtn: 'Verificar Identidad y Restablecer',
    backToLogin: 'Volver a Iniciar Sesión',
    selectLang: 'Idioma',
    categories: 'Categorías',
    latestArticles: 'Últimas Guías de SEO y Fórmulas',
    frequentlyAsked: 'Preguntas Frecuentes',
    conversionHistory: 'Registro de Conversiones en Tiempo Real',
    from: 'De',
    to: 'A',
    value: 'Valor',
    result: 'Resultado de Conversión',
    convertBtn: 'Calcular y Convertir',
    formula: 'Fórmula de Conversión Utilizada:',
    example: 'Ejemplo Práctico:',
    views: 'vistas',
    searchPlaceholder: 'Buscar fórmulas de unidades, calculadoras o guías SEO...',
    adminWelcome: 'Bienvenido al Panel de Administración',
    visitorLogs: 'Registro de Análisis de Visitantes',
    siteSettings: 'Configuración del Sitio',
    adManagement: 'Gestión de Publicidad',
    manageArticles: 'Gestionar Artículos de SEO',
    manageFAQs: 'Gestionar Preguntas Frecuentes',
    saveSettings: 'Guardar Cambios de Configuración',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    createArticle: 'Crear Nuevo Artículo SEO',
    createFAQ: 'Crear Nueva Pregunta Frecuente',
    ipAddress: 'Dirección IP',
    userAgent: 'Agente de Usuario Web',
    visitedAt: 'Hora de Visita',
    path: 'Ruta de Web Solicitada'
  },
  ur: {
    title: 'GlobalConverter',
    subtitle: 'پیشہ ورانہ یونٹ اور کرنسی کنورٹر',
    home: 'ہوم',
    converters: 'کنورٹرز',
    calculators: 'کیلکولیٹرز',
    guides: 'بلاگ گائیڈز',
    admin: 'ایڈمن پینل',
    signIn: 'سائن ان کریں',
    signOut: 'سائن آؤٹ',
    username: 'صارف کا نام یا ای میل',
    password: 'پاس ورڈ',
    login: 'محفوظ طریقے سے سائن ان کریں',
    forgotPassword: 'پاس ورڈ بھول گئے؟',
    fullNameLabel: 'رجسٹرڈ پورا نام (شناخت کی تصدیق کے لیے)',
    newPasswordLabel: 'نیا پاس ورڈ',
    resetPasswordBtn: 'تصدیق کریں اور پاس ورڈ تبدیل کریں',
    backToLogin: 'سائن ان پر واپس جائیں',
    selectLang: 'زبان',
    categories: 'اقسام',
    latestArticles: 'تازہ ترین SEO گائیڈز اور فارمولے',
    frequentlyAsked: 'اکثر پوچھے گئے سوالات',
    conversionHistory: 'ریئل ٹائم تبادلوں کا لاگ',
    from: 'سے',
    to: 'تک',
    value: 'مقدار',
    result: 'امکان تبدیل شدہ نتیجہ',
    convertBtn: 'تبدیل اور حساب کتاب کریں',
    formula: 'استعمال شدہ کنورژن فارمولہ:',
    example: 'عملی مثال:',
    views: 'مناظر',
    searchPlaceholder: 'یونٹ فارمولے، کیلکولیٹر یا SEO گائیڈ تلاش کریں...',
    adminWelcome: 'ایڈمنسٹریٹر پینل میں خوش آمدید',
    visitorLogs: 'زائرین کا تجزیاتی ریکارڈ',
    siteSettings: 'سائٹ کی ترتیبات',
    adManagement: 'اشتہارات کا انتظام',
    manageArticles: 'SEO آرٹیکلز کا انتظام',
    manageFAQs: 'اکثر پوچھے گئے سوالات کا انتظام',
    saveSettings: 'ترتیبات کی تبدیلیاں محفوظ کریں',
    cancel: 'منسوخ کریں',
    edit: 'ترمیم کریں',
    delete: 'حذف کریں',
    createArticle: 'نیا SEO آرٹیکل بنائیں',
    createFAQ: 'نیا اکثر پوچھا جانے والا سوال بنائیں',
    ipAddress: 'آئی پی ایڈریس',
    userAgent: 'یوزر ایجنٹ',
    visitedAt: 'آمد کا وقت',
    path: 'درخواست کردہ ویب پیج'
  }
};

export const INITIAL_RATES = {
  USD: 1,
  EUR: 0.92,
  GBP: 0.78,
  JPY: 156.40,
  AUD: 1.51,
  CAD: 1.37,
  CHF: 0.90,
  CNY: 7.24,
  INR: 83.50,
  PKR: 278.30
};

export const DEFAULT_CATEGORIES: Category[] = [
  { id: 1, name: 'Length Converter', slug: 'length-converter' },
  { id: 2, name: 'Weight Converter', slug: 'weight-converter' },
  { id: 3, name: 'Temperature Converter', slug: 'temperature-converter' },
  { id: 4, name: 'Area Converter', slug: 'area-converter' },
  { id: 5, name: 'Volume Converter', slug: 'volume-converter' }
];

export const DEFAULT_ARTICLES: Article[] = [
  {
    id: 1,
    title: 'How to Convert Meters to Feet (m to ft) Formula',
    slug: 'meters-to-feet-conversion',
    category_id: 1,
    meta_title: 'Meters to Feet Conversion Formula & Guide',
    meta_description: 'Learn how to convert meters into feet easily with our step-by-step math guide, conversion formula and easy dynamic examples.',
    image_url: 'https://images.unsplash.com/photo-1501167786227-4cba60f6d58f?w=600',
    views: 42,
    is_seo_page: true,
    created_at: '2026-06-01T00:00:00Z',
    content: 'Converting meters to feet is one of the most common length conversions in engineering, construction, and everyday life. A meter is the fundamental unit of length in the International System of Units (SI), whereas the foot is an Imperial unit of length.',
    formula: 'Feet = Meters × 3.28084',
    example: 'To convert 5 meters to feet: 5 × 3.28084 = 16.4042 feet.'
  },
  {
    id: 2,
    title: 'Kilograms to Pounds (kg to lbs) Complete Guide',
    slug: 'kilograms-to-pounds-conversion',
    category_id: 2,
    meta_title: 'Convert Kg to Lbs - Kilograms to Pounds Formula',
    meta_description: 'An exhaustive standard reference guide for translating metric mass (kilograms) into imperial units (pounds) easily.',
    image_url: 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=600',
    views: 29,
    is_seo_page: true,
    created_at: '2026-06-02T00:00:00Z',
    content: 'The kilogram is the base unit of mass in the SI system, while the pound is the unit of force/mass in the British imperial system. Knowing how to quickly shift dimensions between the two is vital globally.',
    formula: 'Pounds = Kilograms × 2.20462',
    example: 'For a body weight of 70 Kilograms: 70 × 2.20462 = 154.3234 pounds.'
  },
  {
    id: 3,
    title: 'Celsius to Fahrenheit (C to F) Temperature Conversion',
    slug: 'celsius-to-fahrenheit-conversion',
    category_id: 3,
    meta_title: 'Celsius to Fahrenheit Formula & Temperature Scale Guide',
    meta_description: 'Master the scale calculation to transform Celsius degrees to Fahrenheit quickly with formula explanation and thermal context.',
    image_url: 'https://images.unsplash.com/photo-1542451313-0e3100f725d6?w=600',
    views: 61,
    is_seo_page: true,
    created_at: '2026-06-03T00:00:00Z',
    content: 'Thermometric scales display different intervals for water freezing and boiling points. Celsius measures standard water ice/vapor boundaries from 0 to 100 degrees, whereas Fahrenheit segments that space from 32 to 212 degrees.',
    formula: 'Fahrenheit = (Celsius × 9/5) + 32',
    example: 'Water at body heat of 37 degrees Celsius is: (37 × 1.8) + 32 = 98.6 degrees Fahrenheit.'
  }
];

export const DEFAULT_FAQS: FAQ[] = [
  {
    id: 1,
    question: 'How accurate is the currency converter rates?',
    answer: 'The rates are synchronized dynamically with central financial systems hourly. However, nominal values are subject to regional variations.',
    parent_type: 'app',
    parent_id: 'general'
  },
  {
    id: 2,
    question: 'Can I perform scientific weight conversions?',
    answer: 'Yes! The custom unit converter handles microscopic and colossal weights including metric tons, micrograms, stone, ounce and pounds reliably.',
    parent_type: 'app',
    parent_id: 'general'
  }
];
